### ISSUE TITLE
Angle complement

### ISSUE THREAD

**Issue by vkleen** [puffnfresh/sonic2#9]
Hi Brian,

while watching the youtube recording of the angle data stream, I noticed that you seem to have an off-by-one error when flipping the angles. The ROM negates the angle, while you take the bitwise complement. But in two's complement the negative is the bit complement *plus one*.

So, in collideWithLevel in Main.hs, I think you want
```
 angle' =
    (if flipX then ((+1) . complement) else id) $ reindexedCurves ! blockIndex
```
Maybe, there actually is a function in Data.Word to do this. I haven't checked.

Of course, that's probably not important for getting the visuals correct, but as a mathematician I had to tell you ;)

Viktor

**Comment by vkleen** [comment]
Okay, I did check Data.Word. `negate` is defined by conversion to Int and then properly inverting. So you should be able to just do
```
angle' =
  (if flipX then negate else id) $ reindexedCurves ! blockIndex
```

**Comment by puffnfresh** [comment]
Thanks for watching and thanks for noticing!!! :heart: :heart: :heart:
